[package]
name = "quack-prototype"
version = "0.1.0"
edition = "2021"

[dependencies]
duckdb = { version = "0.10.0", features = ["bundled"] }
once_cell = "1.19.0"
log = "0.4.21"

[dev-dependencies]
env_logger = "0.9.0"

